-- V1: Schema inicial completo.
-- Em bancos existentes (criados pelo ddl-auto=update anterior) este script NUNCA roda:
-- baseline-on-migrate=true + baseline-version=1 marca o banco como "já em V1" e salta direto para V2.
-- Em instalações novas (CI, staging limpo, novos devs) este script cria tudo do zero.

-- ── Tabelas de referência ──────────────────────────────────────────────────

CREATE TABLE states (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null,
    abbreviation varchar(2) not null unique
);

CREATE TABLE cities (
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    state_id bigint not null references states(id)
);

CREATE TABLE business_types (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    slug varchar(255) not null unique
);

CREATE TABLE admin_users (
    id         uuid primary key,
    email      varchar(255) not null unique,
    password   varchar(255) not null,
    name       varchar(255) not null,
    active     boolean      not null default true,
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);

-- ── Lojas ──────────────────────────────────────────────────────────────────

CREATE TABLE stores (
    id                              uuid primary key,
    email                           varchar(255) not null unique,
    password                        varchar(255) not null,
    user_name                       varchar(255) not null,
    store_name                      varchar(255) not null,
    slug                            varchar(255) unique,
    whatsapp_number                 varchar(255),
    store_description               varchar(500),
    logo_url                        varchar(255),
    cover_image_url                 varchar(255),
    is_active                       boolean      not null default true,
    profile_type                    varchar(255) not null default 'STANDARD',
    email_verified                  boolean      not null default false,
    email_verification_token        varchar(36)  unique,
    email_verification_token_expires_at timestamptz,
    theme_config                    jsonb,
    state_id                        bigint references states(id),
    city_id                         bigint references cities(id),
    business_type_id                bigint references business_types(id),
    created_at                      timestamptz  not null,
    updated_at                      timestamptz  not null
);

CREATE TABLE store_promo_images (
    store_id    uuid    not null references stores(id),
    image_url   varchar(255) not null,
    image_order integer not null
);

CREATE TABLE store_slug_history (
    id          bigint generated by default as identity primary key,
    store_id    uuid        not null references stores(id),
    slug        varchar(255) not null unique,
    replaced_at timestamptz not null
);

-- ── Catálogo ───────────────────────────────────────────────────────────────

CREATE TABLE product_types (
    id               bigint generated by default as identity primary key,
    store_id         uuid         not null references stores(id),
    product_type_key varchar(255) not null,
    label            varchar(255) not null,
    sort_order       integer      not null default 0,
    unique (store_id, product_type_key)
);

CREATE TABLE attribute_definitions (
    id              bigint generated by default as identity primary key,
    store_id        uuid         not null references stores(id),
    product_type_id bigint references product_types(id),
    attribute_key   varchar(255) not null,
    label           varchar(255) not null,
    type            varchar(255) not null,
    unit            varchar(255),
    required        boolean      not null default false,
    filterable      boolean      not null default true,
    sort_order      integer      not null default 0,
    unique (store_id, product_type_id, attribute_key)
);

CREATE TABLE attribute_definition_options (
    attribute_definition_id bigint  not null references attribute_definitions(id),
    option_value            varchar(255),
    option_order            integer not null
);

CREATE TABLE products (
    id              bigint generated by default as identity primary key,
    store_id        uuid           not null references stores(id),
    product_type_id bigint         not null references product_types(id),
    name            varchar(255)   not null,
    description     varchar(2000),
    price           numeric(10, 2),
    is_visible      boolean        not null default true,
    featured        boolean        not null default false,
    sort_order      integer,
    affiliate_url   varchar(2048),
    attributes      jsonb,
    updated_at      timestamptz
);

CREATE TABLE product_images (
    product_id  bigint       not null references products(id),
    image_url   varchar(2048) not null,
    image_order integer      not null
);

-- ── Assinaturas ────────────────────────────────────────────────────────────

CREATE TABLE plan_limits (
    id                       bigint generated by default as identity primary key,
    plan                     varchar(255) not null unique,
    max_products             integer      not null,
    max_product_types        integer      not null,
    max_featured_products    integer      not null,
    max_promo_images         integer      not null,
    affiliate_profile_allowed boolean     not null,
    custom_domain_allowed     boolean     not null
);

CREATE TABLE subscriptions (
    id               bigint generated by default as identity primary key,
    store_id         uuid         not null unique references stores(id),
    plan             varchar(255) not null default 'FREE',
    status           varchar(255) not null default 'TRIAL',
    started_at       timestamptz  not null,
    trial_ends_at    timestamptz,
    expires_at       timestamptz,
    cancelled_at     timestamptz,
    payment_provider varchar(255),
    external_id      varchar(255),
    created_at       timestamptz  not null,
    updated_at       timestamptz  not null
);

-- ── Sessões e segurança ────────────────────────────────────────────────────

CREATE TABLE refresh_tokens (
    id         bigint generated by default as identity primary key,
    store_id   uuid        not null references stores(id),
    token_hash varchar(255) not null unique,
    expires_at timestamptz not null,
    revoked    boolean     not null default false,
    created_at timestamptz not null
);

-- ── Carrinho e pedidos ────────────────────────────────────────────────────

CREATE TABLE carts (
    id             uuid         primary key,
    store_id       uuid         not null references stores(id),
    customer_name  varchar(255),
    customer_email varchar(255),
    customer_phone varchar(255),
    status         varchar(255) not null default 'ACTIVE',
    created_at     timestamptz  not null,
    updated_at     timestamptz  not null
);

CREATE TABLE cart_items (
    id           bigint generated by default as identity primary key,
    cart_id      uuid           not null references carts(id),
    product_id   bigint references products(id),
    product_name varchar(255)   not null,
    unit_price   numeric(12, 2) not null,
    quantity     integer        not null default 1
);

CREATE TABLE orders (
    id               uuid           primary key,
    store_id         uuid references stores(id),   -- nullable: preservado após deleção da loja
    customer_name    varchar(255)   not null,
    customer_email   varchar(255),
    customer_phone   varchar(255),
    customer_address varchar(255),
    notes            varchar(1000),
    status           varchar(255)   not null default 'PENDING',
    total_amount     numeric(12, 2) not null,
    created_at       timestamptz    not null,
    updated_at       timestamptz    not null
);

CREATE TABLE order_items (
    id           bigint generated by default as identity primary key,
    order_id     uuid           not null references orders(id),
    product_id   bigint,                            -- sem FK: snapshot do produto no momento da venda
    product_name varchar(255)   not null,
    unit_price   numeric(12, 2) not null,
    quantity     integer        not null
);

-- ── Analytics ─────────────────────────────────────────────────────────────

CREATE TABLE whatsapp_clicks (
    id         bigint generated by default as identity primary key,
    product_id bigint      not null references products(id),
    clicked_at timestamptz not null
);

CREATE TABLE affiliate_clicks (
    id         bigint generated by default as identity primary key,
    product_id bigint      not null references products(id),
    clicked_at timestamptz not null
);
