-- V2: Branch pvd-system — PDV, endereço da loja, controle de estoque.
-- Todos os ALTER TABLE usam ADD COLUMN IF NOT EXISTS e CREATE TABLE IF NOT EXISTS:
-- seguro rodar em bancos que já aplicaram parte dessas mudanças via ddl-auto=update.

-- ── Endereço da loja (campos opcionais) ───────────────────────────────────

ALTER TABLE stores
    ADD COLUMN IF NOT EXISTS address_street       varchar(255),
    ADD COLUMN IF NOT EXISTS address_number       varchar(255),
    ADD COLUMN IF NOT EXISTS address_neighborhood varchar(255),
    ADD COLUMN IF NOT EXISTS address_zip_code     varchar(9);

-- ── Controle de estoque nos produtos ──────────────────────────────────────
-- DEFAULT obrigatório: ADD COLUMN NOT NULL sem DEFAULT falha se a tabela já tem linhas.

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS track_stock    boolean not null default false,
    ADD COLUMN IF NOT EXISTS stock_quantity integer not null default 0;

-- ── PDV — Funcionários ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pdv_employees (
    id         uuid         primary key,
    store_id   uuid         not null references stores(id),
    name       varchar(100) not null,
    pin_hash   varchar(255) not null,
    role       varchar(50)  not null default 'CASHIER',
    is_active  boolean      not null default true,
    created_at timestamptz  not null
);

-- ── PDV — Vendas ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pdv_customers (
    id         uuid         primary key,
    store_id   uuid         not null references stores(id),
    name       varchar(255) not null,
    phone      varchar(255),
    cpf        varchar(14),
    address    varchar(255),
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);

CREATE TABLE IF NOT EXISTS pdv_sales (
    id             uuid           primary key,
    store_id       uuid           not null references stores(id),
    customer_id    uuid           references pdv_customers(id),
    operator_id    uuid           references pdv_employees(id),
    offline_id     varchar(36)    not null,
    payment_method varchar(50)    not null,
    total_amount   numeric(12, 2) not null,
    amount_paid    numeric(12, 2) not null,
    change_amount  numeric(12, 2) not null,
    status         varchar(50)    not null default 'COMPLETED',
    note           varchar(500),
    sale_date      timestamptz    not null,
    synced_at      timestamptz    not null,
    unique (store_id, offline_id)
);

CREATE TABLE IF NOT EXISTS pdv_sale_items (
    id           bigint generated by default as identity primary key,
    sale_id      uuid           not null references pdv_sales(id),
    product_id   bigint,                    -- sem FK: produto pode ser deletado após a venda
    product_name varchar(255)   not null,
    unit_price   numeric(12, 2) not null,
    quantity     integer        not null,
    subtotal     numeric(12, 2) not null
);

-- ── PDV — Fluxo de caixa ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pdv_cash_flows (
    id          uuid           primary key,
    store_id    uuid           not null references stores(id),
    operator_id uuid           references pdv_employees(id),
    offline_id  varchar(36)    not null,
    type        varchar(10)    not null,
    category    varchar(50)    not null,
    amount      numeric(12, 2) not null,
    description varchar(500),
    flow_date   timestamptz    not null,
    synced_at   timestamptz    not null,
    unique (store_id, offline_id)
);

-- ── PDV — Crédito de clientes (promissórias) ──────────────────────────────

CREATE TABLE IF NOT EXISTS pdv_customer_credits (
    id             uuid           primary key,
    customer_id    uuid           not null references pdv_customers(id),
    origin_sale_id uuid,                    -- sem FK: evita bloquear cancelamento de venda
    total_due      numeric(12, 2) not null,
    amount_paid    numeric(12, 2) not null default 0,
    due_date       timestamptz,
    status         varchar(50)    not null default 'OPEN',
    note           varchar(500),
    created_at     timestamptz    not null,
    updated_at     timestamptz    not null
);

CREATE TABLE IF NOT EXISTS pdv_credit_payments (
    id             bigint generated by default as identity primary key,
    credit_id      uuid           not null references pdv_customer_credits(id),
    amount         numeric(12, 2) not null,
    payment_method varchar(50)    not null,
    paid_at        timestamptz    not null,
    created_at     timestamptz    not null
);

-- ── Renomear client_uuid → offline_id (bancos criados via ddl-auto=update) ───
-- DO block: só executa o RENAME se a coluna antiga ainda existir.
-- Em bancos novos (criados pelo V1+V2 acima) a coluna já se chama offline_id — bloco ignorado.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'pdv_sales' AND column_name = 'client_uuid') THEN
        ALTER TABLE pdv_sales RENAME COLUMN client_uuid TO offline_id;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'pdv_cash_flows' AND column_name = 'client_uuid') THEN
        ALTER TABLE pdv_cash_flows RENAME COLUMN client_uuid TO offline_id;
    END IF;
END $$;

-- ── Índices de desempenho ─────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pdv_sales_store_date    ON pdv_sales    (store_id, sale_date DESC);
CREATE INDEX IF NOT EXISTS idx_pdv_cashflow_store_date ON pdv_cash_flows (store_id, flow_date DESC);
CREATE INDEX IF NOT EXISTS idx_pdv_customers_store     ON pdv_customers (store_id);
CREATE INDEX IF NOT EXISTS idx_pdv_credits_customer    ON pdv_customer_credits (customer_id);
