-- Substitui business_types por store_templates.
-- store_templates: presets curados pela plataforma (Vestuário, Imóveis, etc.)
-- que determinam o layoutMode da loja e servem de base para o bootstrap
-- de ProductTypes e AttributeDefinitions no cadastro.

CREATE TABLE store_templates (
    id          bigint generated by default as identity primary key,
    name        varchar(255) not null unique,
    slug        varchar(255) not null unique,
    layout_mode varchar(10)  not null default 'LOJA',
    description varchar(255)
);

-- Adiciona referência ao template e layout_mode direto na loja.
-- layout_mode na loja permite override independente do template (ex: admin ajusta
-- sem mudar o template escolhido pela loja).
ALTER TABLE stores
    ADD COLUMN IF NOT EXISTS store_template_id bigint references store_templates(id),
    ADD COLUMN IF NOT EXISTS layout_mode varchar(10) not null default 'LOJA';

-- Remove a coluna antiga de business_type (zero lojas a usavam).
ALTER TABLE stores
    DROP COLUMN IF EXISTS business_type_id;

-- Remove tabela antiga — zero lojas referenciavam, drop seguro.
DROP TABLE IF EXISTS business_types;
