-- Catálogo de produtos de gasto (lookup leve, busca por nome, com controle de estoque)
CREATE TABLE expense_products (
    id             bigint generated by default as identity primary key,
    store_id       uuid         not null references stores(id),
    name           varchar(255) not null,
    unit           varchar(50),
    stock_quantity integer      not null default 0,
    unique (store_id, name)
);
CREATE INDEX idx_expense_products_store ON expense_products (store_id, name);

-- Batch de gastos unitários (o "cupom" de compra)
CREATE TABLE expense_batches (
    id           uuid           primary key,
    store_id     uuid           not null references stores(id),
    offline_id   varchar(36)    not null,
    operator_id  uuid           references pdv_employees(id),
    note         varchar(500),
    batch_date   timestamptz    not null,
    total_amount numeric(12,2)  not null default 0,
    synced_at    timestamptz    not null,
    unique (store_id, offline_id)
);
CREATE INDEX idx_expense_batches_store_date ON expense_batches (store_id, batch_date DESC);

-- Itens do batch (snapshot de nome — produto pode ser deletado)
CREATE TABLE expense_batch_items (
    id                 bigint generated by default as identity primary key,
    batch_id           uuid           not null references expense_batches(id) on delete cascade,
    expense_product_id bigint,
    product_name       varchar(255)   not null,
    unit               varchar(50),
    unit_price         numeric(12,2)  not null,
    quantity           integer        not null default 1,
    subtotal           numeric(12,2)  not null
);

-- Gastos recorrentes (contas fixas)
CREATE TABLE recurring_expenses (
    id                uuid           primary key,
    store_id          uuid           not null references stores(id),
    name              varchar(255)   not null,
    description       varchar(500),
    amount            numeric(12,2)  not null,
    frequency         varchar(50)    not null,
    due_day           integer        not null,
    alert_days_before integer        not null default 7,
    next_due_date     date           not null,
    last_paid_date    date,
    is_active         boolean        not null default true,
    created_at        timestamptz    not null,
    updated_at        timestamptz    not null
);
CREATE INDEX idx_recurring_store_due ON recurring_expenses (store_id, next_due_date);
