-- V8: Email no cadastro de cliente e tabela de relacionamentos familiares.

-- ── pdv_customers: campo de e-mail ───────────────────────────────────────────
ALTER TABLE pdv_customers
    ADD COLUMN IF NOT EXISTS email varchar(255);

-- ── Relacionamentos familiares entre clientes da mesma loja ──────────────────
CREATE TABLE IF NOT EXISTS pdv_customer_relationships (
    id            bigint generated by default as identity primary key,
    store_id      uuid         not null references stores(id),
    customer_id   uuid         not null references pdv_customers(id),
    relative_id   uuid         not null references pdv_customers(id),
    relationship  varchar(50)  not null,
    note          varchar(255),
    created_at    timestamptz  not null,
    CONSTRAINT uq_customer_relative UNIQUE (customer_id, relative_id),
    CONSTRAINT chk_not_self         CHECK  (customer_id <> relative_id)
);

CREATE INDEX IF NOT EXISTS idx_customer_rel_customer ON pdv_customer_relationships (customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_rel_relative ON pdv_customer_relationships (relative_id);
CREATE INDEX IF NOT EXISTS idx_customer_rel_store    ON pdv_customer_relationships (store_id);
