-- Atributos ENUM deixam de vir com valores pre-definidos: cada loja passa a cadastrar seus
-- proprios valores. Cria a tabela nova (store_attribute_options — valores que cada loja
-- registrou pra um atributo ENUM global) e limpa os valores globais ja seedados que estao
-- no banco hoje (o DataInitializer, por ser idempotente por slug, nao reescreve verticais
-- ja existentes sozinho).
--
-- Necessario porque producao roda com spring.jpa.hibernate.ddl-auto=validate (nunca cria
-- schema sozinho) — ver application-prod.properties.
--
-- Idempotente: seguro rodar mais de uma vez (IF NOT EXISTS / DELETE sem WHERE residual).
--
-- QUANDO RODAR: antes do deploy do codigo novo (mesmo motivo do script de
-- add-business-type-attributes — o codigo novo passa a ler/gravar store_attribute_options
-- assim que subir).

BEGIN;

-- 1. Valores que cada loja cadastrou pra um atributo ENUM global (nao vaza entre lojas —
--    atributos custom continuam usando attribute_definition_options, ja exclusivos da loja).
CREATE TABLE IF NOT EXISTS store_attribute_options (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id                 uuid NOT NULL REFERENCES stores(id),
    attribute_definition_id  bigint NOT NULL REFERENCES attribute_definitions(id),
    option_value             varchar(255) NOT NULL,
    option_order             integer NOT NULL
);

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.table_name = 'store_attribute_options' AND tc.constraint_type = 'UNIQUE'
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'store_attribute_options' AND column_name = 'store_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'store_attribute_options' AND column_name = 'attribute_definition_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'store_attribute_options' AND column_name = 'option_value')
    ) THEN
        ALTER TABLE store_attribute_options
            ADD CONSTRAINT uk_store_attribute_options_store_attr_value
            UNIQUE (store_id, attribute_definition_id, option_value);
    END IF;
END $$;

-- 2. Limpa os valores pre-definidos que ja estao nos atributos ENUM globais (store_id IS
--    NULL) — dai em diante cada loja cadastra o que precisar via
--    POST /api/products/store/{storeId}/attributes/{id}/options. Atributos custom (store_id
--    preenchido) ficam intactos — ja sao exclusivos de quem os criou.
DELETE FROM attribute_definition_options
 WHERE attribute_definition_id IN (
     SELECT id FROM attribute_definitions WHERE store_id IS NULL
 );

-- Verificacao antes de COMMIT
SELECT table_name FROM information_schema.tables WHERE table_name = 'store_attribute_options';
SELECT count(*) AS opcoes_globais_restantes FROM attribute_definition_options ado
 JOIN attribute_definitions ad ON ad.id = ado.attribute_definition_id
 WHERE ad.store_id IS NULL;

-- A segunda consulta deve retornar 0. Se bater, rode:
COMMIT;
-- Caso contrario, rode ROLLBACK; e investigue antes de tentar de novo.
