-- Cria o schema do sistema de tipos de negocio/atributos dinamicos
-- (BusinessType/AttributeDefinition/Product.attributes/Store.businessType), incluindo
-- atributos customizados por loja (AttributeDefinition.store) e o opt-out de atributos
-- globais (store_hidden_attributes).
--
-- Necessario porque producao roda com spring.jpa.hibernate.ddl-auto=validate
-- (nunca cria schema sozinho) — ver application-prod.properties.
--
-- Idempotente: seguro rodar mesmo que parte do schema ja exista (usa
-- IF NOT EXISTS / IF EXISTS em tudo). DDL exato conferido contra o schema que
-- o Hibernate realmente gera (validado localmente antes de escrever este script).
--
-- IMPORTANTE: isso so cria as TABELAS/COLUNAS vazias. Os dados de seed (os 5
-- tipos de negocio — Automoveis, Imoveis, Roupas, Arte, Alimentos — e seus
-- atributos) sao inseridos automaticamente pelo DataInitializer no primeiro
-- boot da aplicacao contra essas tabelas vazias (CommandLineRunner, idempotente
-- via count() > 0) — nao precisa (e nao deve) inserir isso via SQL.
--
-- QUANDO RODAR: antes do deploy do codigo novo (ao contrario do script de
-- remocao de category/material, que roda DEPOIS do deploy).

BEGIN;

-- 1. Tabela de tipos de negocio
CREATE TABLE IF NOT EXISTS business_types (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL
);

-- Checa por QUALQUER unique constraint já existente na coluna (não só pelo nome
-- específico abaixo) — evita duplicar a constraint que o Hibernate já criou com
-- um nome auto-gerado diferente.
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        JOIN information_schema.constraint_column_usage ccu
          ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
        WHERE tc.table_name = 'business_types' AND tc.constraint_type = 'UNIQUE'
          AND ccu.column_name = 'name'
    ) THEN
        ALTER TABLE business_types ADD CONSTRAINT uk_business_types_name UNIQUE (name);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        JOIN information_schema.constraint_column_usage ccu
          ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
        WHERE tc.table_name = 'business_types' AND tc.constraint_type = 'UNIQUE'
          AND ccu.column_name = 'slug'
    ) THEN
        ALTER TABLE business_types ADD CONSTRAINT uk_business_types_slug UNIQUE (slug);
    END IF;
END $$;

-- 2. Definicao de atributos por tipo de negocio. store_id nulo = atributo global
--    da vertical (seed); preenchido = atributo customizado, exclusivo dessa loja.
CREATE TABLE IF NOT EXISTS attribute_definitions (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type_id  bigint NOT NULL REFERENCES business_types(id),
    store_id          uuid REFERENCES stores(id),
    attribute_key     varchar(255) NOT NULL,
    label             varchar(255) NOT NULL,
    type              varchar(255) NOT NULL
        CHECK (type IN ('NUMBER', 'TEXT', 'ENUM', 'BOOLEAN', 'DATE')),
    unit              varchar(255),
    required          boolean NOT NULL,
    filterable        boolean NOT NULL,
    sort_order        integer NOT NULL
);

-- Se a coluna ja existia sem store_id (versao anterior deste script), adiciona agora.
ALTER TABLE attribute_definitions ADD COLUMN IF NOT EXISTS store_id uuid REFERENCES stores(id);

-- Remove qualquer unique constraint de 2 colunas (business_type_id, attribute_key)
-- de uma versao anterior deste script/schema — ela impediria duas lojas diferentes
-- de usarem a mesma chave customizada, o que agora e permitido.
DO $$
DECLARE
    old_constraint record;
BEGIN
    FOR old_constraint IN
        SELECT tc.constraint_name FROM information_schema.table_constraints tc
        WHERE tc.table_name = 'attribute_definitions' AND tc.constraint_type = 'UNIQUE'
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'business_type_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'attribute_key')
          AND tc.constraint_name NOT IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'store_id')
    LOOP
        EXECUTE format('ALTER TABLE attribute_definitions DROP CONSTRAINT %I', old_constraint.constraint_name);
    END LOOP;
END $$;

DO $$
DECLARE
    already_exists boolean;
BEGIN
    SELECT EXISTS (
        SELECT tc.constraint_name FROM information_schema.table_constraints tc
        WHERE tc.table_name = 'attribute_definitions' AND tc.constraint_type = 'UNIQUE'
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'business_type_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'store_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'attribute_key')
    ) INTO already_exists;

    IF NOT already_exists THEN
        ALTER TABLE attribute_definitions
            ADD CONSTRAINT uk_attribute_definitions_type_store_key UNIQUE (business_type_id, store_id, attribute_key);
    END IF;
END $$;

-- 3. Opcoes de atributos ENUM
CREATE TABLE IF NOT EXISTS attribute_definition_options (
    attribute_definition_id bigint NOT NULL REFERENCES attribute_definitions(id),
    option_value             varchar(255),
    option_order             integer NOT NULL,
    PRIMARY KEY (attribute_definition_id, option_order)
);

-- 4. Loja escolhe um tipo de negocio (nullable — lojas existentes ficam sem ate editarem)
ALTER TABLE stores ADD COLUMN IF NOT EXISTS business_type_id bigint;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
        WHERE tc.table_name = 'stores' AND tc.constraint_type = 'FOREIGN KEY'
          AND kcu.column_name = 'business_type_id'
    ) THEN
        ALTER TABLE stores
            ADD CONSTRAINT fk_stores_business_type FOREIGN KEY (business_type_id) REFERENCES business_types(id);
    END IF;
END $$;

-- 5. Atributos dinamicos do produto (JSON — nullable, mesmo motivo do Store.businessType)
ALTER TABLE products ADD COLUMN IF NOT EXISTS attributes jsonb;

-- 6. Atributos globais que uma loja escolheu esconder (opt-out, sem apagar o original)
CREATE TABLE IF NOT EXISTS store_hidden_attributes (
    store_id                uuid NOT NULL REFERENCES stores(id),
    attribute_definition_id bigint
);

-- Verificacao antes de COMMIT
SELECT table_name FROM information_schema.tables
 WHERE table_name IN ('business_types', 'attribute_definitions', 'attribute_definition_options',
                       'store_hidden_attributes');
SELECT column_name FROM information_schema.columns
 WHERE table_name = 'stores' AND column_name = 'business_type_id';
SELECT column_name, data_type FROM information_schema.columns
 WHERE table_name = 'products' AND column_name = 'attributes';
SELECT column_name FROM information_schema.columns
 WHERE table_name = 'attribute_definitions' AND column_name = 'store_id';

-- Se as três consultas acima retornarem as tabelas/colunas esperadas, rode:
COMMIT;
-- Caso contrário, rode ROLLBACK; e investigue antes de tentar de novo.
