-- Tipo de Produto (ProductType): sub-categorias que a propria loja cria (ex.: "Camisa",
-- "Action Figure"), permitindo escopar AttributeDefinition a um subconjunto dos produtos da
-- loja em vez de todos. Ver domain/model/ProductType.java.
--
-- Necessario porque producao roda com spring.jpa.hibernate.ddl-auto=validate (nunca cria
-- schema sozinho) — ver application-prod.properties.
--
-- Idempotente: seguro rodar mais de uma vez (IF NOT EXISTS / checks via information_schema).
--
-- QUANDO RODAR: antes do deploy do codigo novo — a entidade Product/AttributeDefinition
-- passa a ter FK pra product_types assim que a nova classe subir, e Hibernate valida no
-- boot (ddl-auto=validate) que a coluna/tabela ja existem.

BEGIN;

-- 1. Tipos de produto — sempre pertencem a uma loja, nunca globais/curados pela plataforma.
CREATE TABLE IF NOT EXISTS product_types (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id         uuid NOT NULL REFERENCES stores(id),
    product_type_key varchar(255) NOT NULL,
    label            varchar(255) NOT NULL,
    sort_order       integer NOT NULL
);

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.table_name = 'product_types' AND tc.constraint_type = 'UNIQUE'
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'product_types' AND column_name = 'store_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'product_types' AND column_name = 'product_type_key')
    ) THEN
        ALTER TABLE product_types
            ADD CONSTRAINT uk_product_types_store_key UNIQUE (store_id, product_type_key);
    END IF;
END $$;

-- 2. attribute_definitions ganha FK opcional pra escopar um atributo custom a um ProductType
--    especifico (nulo = atributo geral, aplica em todo produto da loja, como ja era).
ALTER TABLE attribute_definitions ADD COLUMN IF NOT EXISTS product_type_id bigint REFERENCES product_types(id);

-- Remove qualquer unique constraint de 3 colunas (business_type_id, store_id, attribute_key)
-- de uma versao anterior deste schema — ela nao permite duas linhas com a mesma key quando
-- uma e geral e outra e escopada a um ProductType diferente, o que agora e permitido.
DO $$
DECLARE
    old_constraint record;
BEGIN
    FOR old_constraint IN
        SELECT tc.constraint_name FROM information_schema.table_constraints tc
        WHERE tc.table_name = 'attribute_definitions' AND tc.constraint_type = 'UNIQUE'
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'business_type_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'store_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'attribute_key')
          AND tc.constraint_name NOT IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'product_type_id')
    LOOP
        EXECUTE format('ALTER TABLE attribute_definitions DROP CONSTRAINT %I', old_constraint.constraint_name);
    END LOOP;
END $$;

DO $$
DECLARE
    already_exists boolean;
BEGIN
    SELECT EXISTS (
        SELECT tc.constraint_name FROM information_schema.table_constraints tc
        WHERE tc.table_name = 'attribute_definitions' AND tc.constraint_type = 'UNIQUE'
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'business_type_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'store_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'product_type_id')
          AND tc.constraint_name IN (
              SELECT constraint_name FROM information_schema.key_column_usage
              WHERE table_name = 'attribute_definitions' AND column_name = 'attribute_key')
    ) INTO already_exists;

    IF NOT already_exists THEN
        ALTER TABLE attribute_definitions
            ADD CONSTRAINT uk_attribute_definitions_type_store_ptype_key
            UNIQUE (business_type_id, store_id, product_type_id, attribute_key);
    END IF;
END $$;

-- 3. products ganha FK opcional pro tipo de produto (nulo = loja nao usa essa feature).
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type_id bigint REFERENCES product_types(id);

-- Verificacao antes de COMMIT
SELECT table_name FROM information_schema.tables WHERE table_name = 'product_types';
SELECT column_name FROM information_schema.columns
 WHERE table_name = 'attribute_definitions' AND column_name = 'product_type_id';
SELECT column_name FROM information_schema.columns
 WHERE table_name = 'products' AND column_name = 'product_type_id';

-- Se as três consultas acima retornarem as tabelas/colunas esperadas, rode:
COMMIT;
-- Caso contrário, rode ROLLBACK; e investigue antes de tentar de novo.
